-- Auto-generated by gen_boot_paths_pkg.tcl; do not edit.
library ieee;
package boot_paths_pkg is
   constant BOOT0_PATH : string := "/var/home/bazzite/Dokumente/Developer/c128Mega65/sdcard/c128/boot0.rom";
   constant LOG_PATH   : string := "/var/home/bazzite/Dokumente/Developer/c128Mega65/.cursor/debug-b576b7.log";
   constant C_MEM_BRIDGE : boolean := false;
end package boot_paths_pkg;
