// Auto-generated by run_c157x_boot_sim.tcl; do not edit.
package sim_boot1_path_pkg;
   parameter string BOOT1_ROM_PATH = "/var/home/bazzite/Dokumente/Developer/c128Mega65/sdcard/c128/boot1.rom";
   parameter string DRIVE_IMAGE_PATH = "/var/home/bazzite/Dokumente/Developer/c128Mega65/test/157x-rw/157x-rw-test.d64";
   parameter int    DRIVE_IMAGE_BYTES = 174848;
   parameter int    DRIVE_IMAGE_TYPE = 2;
   parameter int    BIT_PHASE_NS   = 120000;
   parameter int    HOST_BYTE_NS   = 0;
endpackage
