## NAME-OF-YOUR-PROJECT for MEGA65 (NAME-OF-THE-GITHUB-REPO)
##
## Core specific constraints
##
## This machine is based on EXACT GITHUB REPO NAME OF THE MiSTer REPO
## Powered by MiSTer2MEGA65
## MEGA65 port done by YOURNAME in YEAR and licensed under GPL v3


## Name Autogenerated Clocks
## Important: Using them in subsequent statements, e.g. clock dividers requires that they
## have been named/defined here before
## otherwise Vivado does not find the pins)
create_generated_clock -name main_clk      [get_pins CORE/clk_gen/i_clk_main/CLKOUT0]
# Add more clocks here, if needed

# Vivado 2022.2 flags this known feedback loop as a hard DRC error.
# Keep the loop acknowledged so bitstream generation can continue.
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets CORE/i_main/cart_reset_o]

# VDC MMCM uses a fractional multiply value that Vivado rounds internally.
# Treat this as warning to avoid blocking bitstream generation.
set_property SEVERITY Warning [get_drc_checks AVAL-139]

