# Generate boot_paths_pkg.vhd with absolute paths for simulation.
set core_dir  [file normalize [file join [file dirname [info script]] ..]]
set repo_dir  [file normalize [file join $core_dir ..]]
set boot_rom  [file join $repo_dir sdcard c128 boot0.rom]
set log_file  [file join $repo_dir .cursor debug-boot.log]
set out_file  [file join $core_dir sim boot_paths_pkg.vhd]

set fh [open $out_file w]
puts $fh "-- Auto-generated by gen_boot_paths_pkg.tcl; do not edit."
puts $fh "library ieee;"
puts $fh "package boot_paths_pkg is"
puts $fh "   constant BOOT0_PATH : string := \"$boot_rom\";"
puts $fh "   constant LOG_PATH   : string := \"$log_file\";"
puts $fh "end package boot_paths_pkg;"
close $fh
puts "Wrote $out_file"
