# Generate boot_paths_pkg.vhd with absolute paths for simulation.
# Caller may set ::sim_mem_bridge to 1 before sourcing (H-V23 regression mode).
if {![info exists ::sim_mem_bridge]} {
    set ::sim_mem_bridge 0
}

set core_dir  [file normalize [file join [file dirname [info script]] ..]]
set repo_dir  [file normalize [file join $core_dir ..]]
set boot_rom  [file join $repo_dir sdcard c128 boot0.rom]
set log_file  [file join $repo_dir .cursor debug-b576b7.log]
set out_file  [file join $core_dir sim boot_paths_pkg.vhd]

if {$::sim_mem_bridge} {
    set mem_bridge_vhdl "true"
} else {
    set mem_bridge_vhdl "false"
}

set fh [open $out_file w]
puts $fh "-- Auto-generated by gen_boot_paths_pkg.tcl; do not edit."
puts $fh "library ieee;"
puts $fh "package boot_paths_pkg is"
puts $fh "   constant BOOT0_PATH : string := \"$boot_rom\";"
puts $fh "   constant LOG_PATH   : string := \"$log_file\";"
puts $fh "   constant C_MEM_BRIDGE : boolean := $mem_bridge_vhdl;"
puts $fh "end package boot_paths_pkg;"
close $fh
puts "Wrote $out_file (C_MEM_BRIDGE=$mem_bridge_vhdl)"
