# Run the 1541/1571 bring-up simulation (tb_c157x_boot).
#
# Mounts a .D64, streams the real boot1.rom into the drive through the same pull
# handshake as the hardware, and checks that the drive CPU starts executing DOS.
# A failure here means the drive is silent on the IEC bus, which the C128 reports
# as "?DEVICE NOT PRESENT" long before any GCR decoding is involved.
#
# Usage:
#   vivado -mode batch -source CORE/scripts/run_c157x_boot_sim.tcl -tclargs CORE/CORE-R6-vivado2022.xpr

# Optional second argument: the IEC half-bit time in nanoseconds. The testbench default
# is a relaxed 120 us; passing the value measured on hardware turns this into a check of
# whether the drive can actually keep up with the host it is wired to.
set project_file [lindex $argv 0]
set bit_phase_ns [lindex $argv 1]
if {$project_file eq ""} {
    set project_file [file normalize [file join [file dirname [info script]] .. CORE-R6-vivado2022.xpr]]
}

set core_dir [file normalize [file join [file dirname [info script]] ..]]
set repo_dir [file normalize [file join $core_dir ..]]
set tb_file  [file join $core_dir sim tb_c157x_boot.sv]
set pkg_file [file join $core_dir sim sim_boot1_path_pkg.sv]
set boot_rom [file join $repo_dir sdcard c128 boot1.rom]

if {![file exists $boot_rom]} {
    puts "ERROR: Missing drive ROM bundle: $boot_rom"
    exit 2
}

# The path is baked into a generated package rather than passed on the command line,
# because xsim runs from its own working directory and ignores simulator options that
# are set after the simulation set has been created.
set d64_image [file join $repo_dir test 157x-rw 157x-rw-test.d64]

if {$bit_phase_ns eq ""} { set bit_phase_ns 120000 }

set fh [open $pkg_file w]
puts $fh "// Auto-generated by run_c157x_boot_sim.tcl; do not edit."
puts $fh "package sim_boot1_path_pkg;"
puts $fh "   parameter string BOOT1_ROM_PATH = \"$boot_rom\";"
puts $fh "   parameter string D64_IMAGE_PATH = \"$d64_image\";"
puts $fh "   parameter int    BIT_PHASE_NS   = $bit_phase_ns;"
puts $fh "endpackage"
close $fh

open_project $project_file
if {[llength [get_filesets -quiet sim_1]] == 0} { create_fileset -simset sim_1 }
foreach f [list $pkg_file $tb_file] {
    if {[llength [get_files -quiet $f]] == 0} {
        add_files -fileset sim_1 -norecurse $f
    }
    set_property file_type {SystemVerilog} [get_files $f]
}
set_property top tb_c157x_boot [get_filesets sim_1]
set_property top_lib xil_defaultlib [get_filesets sim_1]
set_property -name {xsim.elaborate.debug_level} -value {off} -objects [get_filesets sim_1]
update_compile_order -fileset sim_1
launch_simulation -simset sim_1
run 3 s

set sim_dir [file join [file dirname [file normalize $project_file]] \
    "[file rootname [file tail $project_file]].sim" sim_1 behav xsim]
close_sim -force
set gate_ok 0
set sim_log [file join $sim_dir simulate.log]
if {[file exists $sim_log]} {
    set fh [open $sim_log r]
    while {[gets $fh line] >= 0} {
        if {[string match *ALL\ CHECKS\ PASSED* $line]} { set gate_ok 1 }
        if {[string match *PASS* $line] || [string match *FAIL* $line] || \
            [string match *INFO* $line] || [string match *NOTE* $line]} { puts $line }
    }
    close $fh
}
close_project
if {!$gate_ok} { puts "ERROR: tb_c157x_boot failed"; exit 2 }
exit 0
