# Control experiment for the 1541/1571 serial bus bring-up (tb_c1581_iec).
#
# Points the same model of the C128 serial bus at the 1581, which works on real
# hardware. It validates the bus model before its verdict about the 1541/1571 is
# taken seriously.
#
# Usage:
#   vivado -mode batch -source CORE/scripts/run_c1581_iec_sim.tcl -tclargs CORE/CORE-R6-vivado2022.xpr

set project_file [lindex $argv 0]
if {$project_file eq ""} {
    set project_file [file normalize [file join [file dirname [info script]] .. CORE-R6-vivado2022.xpr]]
}

set core_dir [file normalize [file join [file dirname [info script]] ..]]
set repo_dir [file normalize [file join $core_dir ..]]
set tb_file  [file join $core_dir sim tb_c1581_iec.sv]
set pkg_file [file join $core_dir sim sim_boot1_path_pkg.sv]
set boot_rom [file join $repo_dir sdcard c128 boot1.rom]

if {![file exists $boot_rom]} {
    puts "ERROR: Missing drive ROM bundle: $boot_rom"
    exit 2
}

set fh [open $pkg_file w]
puts $fh "// Auto-generated by run_c1581_iec_sim.tcl; do not edit."
puts $fh "package sim_boot1_path_pkg;"
puts $fh "   parameter string BOOT1_ROM_PATH = \"$boot_rom\";"
puts $fh "endpackage"
close $fh

open_project $project_file
if {[llength [get_filesets -quiet sim_1]] == 0} { create_fileset -simset sim_1 }
foreach f [list $pkg_file $tb_file] {
    if {[llength [get_files -quiet $f]] == 0} {
        add_files -fileset sim_1 -norecurse $f
    }
    set_property file_type {SystemVerilog} [get_files $f]
}
set_property top tb_c1581_iec [get_filesets sim_1]
set_property top_lib xil_defaultlib [get_filesets sim_1]
set_property -name {xsim.elaborate.debug_level} -value {off} -objects [get_filesets sim_1]
update_compile_order -fileset sim_1
launch_simulation -simset sim_1
run 3 s

set sim_dir [file join [file dirname [file normalize $project_file]] \
    "[file rootname [file tail $project_file]].sim" sim_1 behav xsim]
close_sim -force
set gate_ok 0
set sim_log [file join $sim_dir simulate.log]
if {[file exists $sim_log]} {
    set fh [open $sim_log r]
    while {[gets $fh line] >= 0} {
        if {[string match *ALL\ CHECKS\ PASSED* $line]} { set gate_ok 1 }
        if {[string match *PASS* $line] || [string match *FAIL* $line] || \
            [string match *INFO* $line]} { puts $line }
    }
    close $fh
}
close_project
if {!$gate_ok} { puts "ERROR: tb_c1581_iec failed"; exit 2 }
