# Run the 1541/1571 read-head stream simulation (tb_c157x_stream).
#
# Checks the join between the GCR encoder and the drive it lives in: with a .D64
# track in the buffer and the VIA2 outputs held at motor-on / read / byte-ready,
# the head has to produce sync marks and a $52 sector header. A drive that fails
# here looks alive on the serial bus but never completes a disk job, so the DOS
# never steps the head and the C128 reports "?FILE NOT FOUND".
#
# This deliberately bypasses the DOS power-up self test, so it finishes in
# seconds rather than the hour tb_c157x_boot needs.
#
# Usage:
#   vivado -mode batch -source CORE/scripts/run_c157x_stream_sim.tcl -tclargs CORE/CORE-R6-vivado2022.xpr

set project_file [lindex $argv 0]
if {$project_file eq ""} {
    set project_file [file normalize [file join [file dirname [info script]] .. CORE-R6-vivado2022.xpr]]
}

set core_dir [file normalize [file join [file dirname [info script]] ..]]
set repo_dir [file normalize [file join $core_dir ..]]
set tb_file  [file join $core_dir sim tb_c157x_stream.sv]
set pkg_file [file join $core_dir sim sim_boot1_path_pkg.sv]
set boot_rom [file join $repo_dir sdcard c128 boot1.rom]

if {![file exists $boot_rom]} {
    puts "ERROR: Missing drive ROM bundle: $boot_rom"
    exit 2
}

set d64_image [file join $repo_dir test 157x-rw 157x-rw-test.d64]

set fh [open $pkg_file w]
puts $fh "// Auto-generated by run_c157x_stream_sim.tcl; do not edit."
puts $fh "package sim_boot1_path_pkg;"
puts $fh "   parameter string BOOT1_ROM_PATH = \"$boot_rom\";"
puts $fh "   parameter string D64_IMAGE_PATH = \"$d64_image\";"
puts $fh "endpackage"
close $fh

source [file join [file dirname [info script]] sim_launch.tcl]

open_project $project_file
if {[llength [get_filesets -quiet sim_1]] == 0} { create_fileset -simset sim_1 }
foreach f [list $pkg_file $tb_file] {
    if {[llength [get_files -quiet $f]] == 0} {
        add_files -fileset sim_1 -norecurse $f
    }
    set_property file_type {SystemVerilog} [get_files $f]
}
set_property -name {xsim.elaborate.debug_level} -value {typical} -objects [get_filesets sim_1]
update_compile_order -fileset sim_1
sim_launch tb_c157x_stream
run 100 ms

set sim_dir [file join [file dirname [file normalize $project_file]] \
    "[file rootname [file tail $project_file]].sim" sim_1 behav xsim]
close_sim -force
set gate_ok 0
set sim_log [file join $sim_dir simulate.log]
if {[file exists $sim_log]} {
    set fh [open $sim_log r]
    while {[gets $fh line] >= 0} {
        if {[string match *ALL\ CHECKS\ PASSED* $line]} { set gate_ok 1 }
        if {[string match *PASS* $line] || [string match *FAIL* $line] || \
            [string match *INFO* $line] || [string match *NOTE* $line]} { puts $line }
    }
    close $fh
}
close_project
if {!$gate_ok} { puts "ERROR: tb_c157x_stream failed"; exit 2 }
exit 0
