# Run the 1541/1571 bring-up simulation (tb_c157x_boot).
#
# Mounts a .D64, streams the real boot1.rom into the drive through the same pull
# handshake as the hardware, and checks that the drive CPU starts executing DOS.
# A failure here means the drive is silent on the IEC bus, which the C128 reports
# as "?DEVICE NOT PRESENT" long before any GCR decoding is involved.
#
# Usage:
#   vivado -mode batch -source CORE/scripts/run_c157x_boot_sim.tcl -tclargs CORE/CORE-R6-vivado2022.xpr

# Optional second argument: the IEC half-bit time in nanoseconds. The testbench default
# is a relaxed 120 us; passing the value measured on hardware turns this into a check of
# whether the drive can actually keep up with the host it is wired to.
# Optional third argument: d64 (default) or d71.
# Optional fourth argument: nanoseconds the host model takes per transferred byte. The
# QNICE shell copies a sector byte by byte through a 4k window, so a real track fetch
# costs milliseconds while the default instant model costs microseconds. Passing the
# measured per-byte cost turns this into a check of whether the drive survives a fetch
# that long.
set project_file [lindex $argv 0]
set bit_phase_ns [lindex $argv 1]
set image_kind [string tolower [lindex $argv 2]]
set host_byte_ns [lindex $argv 3]
if {$project_file eq ""} {
    set project_file [file normalize [file join [file dirname [info script]] .. CORE-R6-vivado2022.xpr]]
}
if {$image_kind eq ""} { set image_kind "d64" }
if {$image_kind ni {"d64" "d71"}} {
    puts "ERROR: image kind must be d64 or d71"
    exit 2
}

set core_dir [file normalize [file join [file dirname [info script]] ..]]
set repo_dir [file normalize [file join $core_dir ..]]
set tb_file  [file join $core_dir sim tb_c157x_boot.sv]
set pkg_file [file join $core_dir sim sim_boot1_path_pkg.sv]
set boot_rom [file join $repo_dir sdcard c128 boot1.rom]

if {![file exists $boot_rom]} {
    puts "ERROR: Missing drive ROM bundle: $boot_rom"
    exit 2
}

# The path is baked into a generated package rather than passed on the command line,
# because xsim runs from its own working directory and ignores simulator options that
# are set after the simulation set has been created.
set image_path [file join $repo_dir test 157x-rw "157x-rw-test.$image_kind"]
if {$image_kind eq "d71"} {
    set image_bytes 349696
    set image_type 3
} else {
    set image_bytes 174848
    set image_type 2
}

if {$bit_phase_ns eq ""} { set bit_phase_ns 120000 }
if {$host_byte_ns eq ""} { set host_byte_ns 0 }

set fh [open $pkg_file w]
puts $fh "// Auto-generated by run_c157x_boot_sim.tcl; do not edit."
puts $fh "package sim_boot1_path_pkg;"
puts $fh "   parameter string BOOT1_ROM_PATH = \"$boot_rom\";"
puts $fh "   parameter string DRIVE_IMAGE_PATH = \"$image_path\";"
puts $fh "   parameter int    DRIVE_IMAGE_BYTES = $image_bytes;"
puts $fh "   parameter int    DRIVE_IMAGE_TYPE = $image_type;"
puts $fh "   parameter int    BIT_PHASE_NS   = $bit_phase_ns;"
puts $fh "   parameter int    HOST_BYTE_NS   = $host_byte_ns;"
puts $fh "endpackage"
close $fh

source [file join [file dirname [info script]] sim_launch.tcl]

open_project $project_file
if {[llength [get_filesets -quiet sim_1]] == 0} { create_fileset -simset sim_1 }
foreach f [list $pkg_file $tb_file] {
    if {[llength [get_files -quiet $f]] == 0} {
        add_files -fileset sim_1 -norecurse $f
    }
    set_property file_type {SystemVerilog} [get_files $f]
}
set_property -name {xsim.elaborate.debug_level} -value {off} -objects [get_filesets sim_1]
update_compile_order -fileset sim_1
sim_launch tb_c157x_boot
run 3 s

set sim_dir [file join [file dirname [file normalize $project_file]] \
    "[file rootname [file tail $project_file]].sim" sim_1 behav xsim]
close_sim -force
set gate_ok 0
set sim_log [file join $sim_dir simulate.log]
if {[file exists $sim_log]} {
    set fh [open $sim_log r]
    while {[gets $fh line] >= 0} {
        if {[string match *ALL\ CHECKS\ PASSED* $line] ||
            [string match *D71\ INIT\ CHECKS\ PASSED* $line]} { set gate_ok 1 }
        if {[string match *PASS* $line] || [string match *FAIL* $line] || \
            [string match *INFO* $line] || [string match *NOTE* $line]} { puts $line }
    }
    close $fh
}
close_project
if {!$gate_ok} { puts "ERROR: tb_c157x_boot failed"; exit 2 }
exit 0
