# Run the 1541/1571 disk controller job simulation (tb_c157x_job).
#
# Posts a read job straight into the drive's own job queue in zero page and reads
# back the status byte the disk controller writes there. That bypasses the serial
# bus completely, so a failure points at the controller, the head or the track
# geometry rather than at IEC timing.
#
# The drive CPU is clocked four times over during the DOS power-up self test, so
# this finishes in minutes rather than the hour tb_c157x_boot needs.
#
# Usage:
#   vivado -mode batch -source CORE/scripts/run_c157x_job_sim.tcl -tclargs CORE/CORE-R6-vivado2022.xpr

set project_file [lindex $argv 0]
if {$project_file eq ""} {
    set project_file [file normalize [file join [file dirname [info script]] .. CORE-R6-vivado2022.xpr]]
}

set core_dir [file normalize [file join [file dirname [info script]] ..]]
set repo_dir [file normalize [file join $core_dir ..]]
set tb_file  [file join $core_dir sim tb_c157x_job.sv]
set pkg_file [file join $core_dir sim sim_boot1_path_pkg.sv]
set boot_rom [file join $repo_dir sdcard c128 boot1.rom]

if {![file exists $boot_rom]} {
    puts "ERROR: Missing drive ROM bundle: $boot_rom"
    exit 2
}

set d64_image [file join $repo_dir test 157x-rw 157x-rw-test.d64]

# Optional second argument picks the job code, e.g. b0 for the seek the DOS
# issues first after a mount. Defaults to 80, a plain sector read.
set job_code [lindex $argv 1]
if {$job_code eq ""} { set job_code 80 }
set force_fast [lindex $argv 2]
if {$force_fast eq ""} { set force_fast 0 }
# Optional fourth argument selects the hardware/ROM model: 10 for 1571, 00 for
# 1541. This lets the same 1 MHz stream test distinguish shared GCR failures
# from 1571 compatibility-interface failures.
set drive_mode [lindex $argv 3]
if {$drive_mode eq ""} { set drive_mode 10 }

set fh [open $pkg_file w]
puts $fh "// Auto-generated by run_c157x_job_sim.tcl; do not edit."
puts $fh "package sim_boot1_path_pkg;"
puts $fh "   parameter string BOOT1_ROM_PATH = \"$boot_rom\";"
puts $fh "   parameter string D64_IMAGE_PATH = \"$d64_image\";"
puts $fh "   parameter bit \[7:0\] JOB_CODE = 8'h$job_code;"
puts $fh "   parameter bit FORCE_FAST = 1'b$force_fast;"
puts $fh "   parameter bit \[1:0\] DRIVE_MODE = 2'b$drive_mode;"
puts $fh "endpackage"
close $fh

open_project $project_file
if {[llength [get_filesets -quiet sim_1]] == 0} { create_fileset -simset sim_1 }
foreach f [list $pkg_file $tb_file] {
    if {[llength [get_files -quiet $f]] == 0} {
        add_files -fileset sim_1 -norecurse $f
    }
    set_property file_type {SystemVerilog} [get_files $f]
}
set_property top tb_c157x_job [get_filesets sim_1]
set_property top_lib xil_defaultlib [get_filesets sim_1]
set_property -name {xsim.elaborate.debug_level} -value {typical} -objects [get_filesets sim_1]
update_compile_order -fileset sim_1
launch_simulation -simset sim_1
run 2 s

set sim_dir [file join [file dirname [file normalize $project_file]] \
    "[file rootname [file tail $project_file]].sim" sim_1 behav xsim]
close_sim -force
set gate_ok 0
set sim_log [file join $sim_dir simulate.log]
if {[file exists $sim_log]} {
    set fh [open $sim_log r]
    while {[gets $fh line] >= 0} {
        if {[string match *ALL\ CHECKS\ PASSED* $line]} { set gate_ok 1 }
        if {[string match *PASS* $line] || [string match *FAIL* $line] || \
            [string match *INFO* $line] || [string match *NOTE* $line]} { puts $line }
    }
    close $fh
}
close_project
if {!$gate_ok} { puts "ERROR: tb_c157x_job failed"; exit 2 }
exit 0
